DROP TABLE CUSTOMER;
DROP TABLE BANK;

CREATE TABLE BANK(
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE) NOT NULL
);
    
CREATE TABLE CUSTOMER(
    CUS_NO NUMBER NOT NULL,
    CUS_NAME VARCHAR2(30 BYTE) NOT NULL,
    CUS_PHONE VARCHAR2(30 BYTE) UNIQUE,
    CUS_AGE NUMBER NULL CHECK (CUS_AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20 BYTE) NULL
);
    
ALTER TABLE BANK
    ADD CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE);
    
ALTER TABLE CUSTOMER
    ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUS_NO);
    
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY(BANK_CODE)
        REFERENCES BANK(BANK_CODE)
            ON DELETE CASCADE;