DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;

CREATE TABLE PROFESSOR(
    PRO_NUM NUMBER NOT NULL,
    PRO_NAME VARCHAR2(30 BYTE) NULL,
    PRO_SUB VARCHAR2(30 BYTE) NULL
);

CREATE TABLE COURSE(
    COU_NUM NUMBER NOT NULL,
    COU_NAME VARCHAR2(30 BYTE) NULL,
    COU_GRA NUMBER(1) NULL
);

CREATE TABLE STUDENT(
    STU_NO NUMBER NOT NULL,
    STU_NAME VARCHAR2(30 BYTE) NULL,
    STU_ADDR VARCHAR2(100 BYTE) NULL,
    STU_GRADE NUMBER(1) NULL,
    STU_PRONUM NUMBER NOT NULL
);

CREATE TABLE ENROLL(
    ENR_NUM NUMBER NOT NULL,
    ENR_NO NUMBER NOT NULL,
    ENR_COUNUM NUMBER NOT NULL,
    ENR_DATE VARCHAR2(15 BYTE) NULL
);

CREATE TABLE LECTURE(
    LEC_NUM NUMBER NOT NULL,
    LEC_PRONUM NUMBER NOT NULL,
    LEC_ENR NUMBER NOT NULL,
    LEC_NAME VARCHAR2(30 BYTE) NULL,
    LEC_ROOM VARCHAR2(30 BYTE) NULL
);
    
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NUM);

ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURESE PRIMARY KEY(COU_NUM);
    
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NUM);

ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NUM);
    
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(STU_PRONUM)
    REFERENCES PROFESSOR(PRO_NUM);
    
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(LEC_PRONUM)
    REFERENCES PROFESSOR(PRO_NUM);

ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(LEC_ENR)
    REFERENCES ENROLL(ENR_NUM);
    
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(ENR_COUNUM)
    REFERENCES COURSE(COU_NUM);

ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(ENR_NO)
    REFERENCES STUDENT(STU_NO);

/* 데이터 삽입 */
INSERT INTO PROFESSOR(PRO_NUM, PRO_NAME, PRO_SUB) VALUES (1, '제임스', '전산');
INSERT INTO PROFESSOR(PRO_NUM, PRO_NAME, PRO_SUB) VALUES (2, '앨리스', '회계');
INSERT INTO PROFESSOR(PRO_NUM, PRO_NAME, PRO_SUB) VALUES (3, '스미스', '영화');

INSERT INTO COURSE(COU_NUM, COU_NAME, COU_GRA) VALUES (11, '자바', 3);
INSERT INTO COURSE(COU_NUM, COU_NAME, COU_GRA) VALUES (22, '데이터베이스', 3);
INSERT INTO COURSE(COU_NUM, COU_NAME, COU_GRA) VALUES (33, '서버프로그램', 3);

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADDR, STU_GRADE, STU_PRONUM) VALUES (10101, '김학생', '서울', 1, 3);
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADDR, STU_GRADE, STU_PRONUM) VALUES (10102, '이학생', '경기', 1, 3);
INSERT INTO STUDENT(STU_NO, STU_NAME, STU_ADDR, STU_GRADE, STU_PRONUM) VALUES (10103, '최학생', '이천', 1, 3);

INSERT INTO ENROLL(ENR_NUM, ENR_NO, ENR_COUNUM, ENR_DATE) VALUES (111, 10101, 11, '20-02-25');
INSERT INTO ENROLL(ENR_NUM, ENR_NO, ENR_COUNUM, ENR_DATE) VALUES (222, 10102, 22, '20-02-26');
INSERT INTO ENROLL(ENR_NUM, ENR_NO, ENR_COUNUM, ENR_DATE) VALUES (333, 10103, 33, '20-02-27');

INSERT INTO LECTURE(LEC_NUM, LEC_PRONUM, LEC_ENR, LEC_NAME, LEC_ROOM) VALUES (1111, 1, 111, '자바완전정복', 'A101');
INSERT INTO LECTURE(LEC_NUM, LEC_PRONUM, LEC_ENR, LEC_NAME, LEC_ROOM) VALUES (2222, 1, 111, '자바완전정복', 'B101');
INSERT INTO LECTURE(LEC_NUM, LEC_PRONUM, LEC_ENR, LEC_NAME, LEC_ROOM) VALUES (3333, 1, 111, '자바완전정복', 'C101');

COMMIT;