DROP TABLE MEMBER_LOG;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY NOT NULL,
    ID VARCHAR2(30 BYTE) UNIQUE NOT NULL,
    PW VARCHAR2(30 BYTE) NOT NULL,
    NAME VARCHAR2(30 BYTE),
    PHONE VARCHAR2(15 BYTE),
    CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO)
);

CREATE TABLE MEMBER_LOG(
    LOG_NO NUMBER PRIMARY KEY NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LOGIN DATE NULL,
    CONSTRAINT MEMBER_LOG_MEMBER_FK FOREIGN KEY(MEMBER_NO)
    REFERENCES MEMBER(MEMBER_NO)
);
